version: '3'

services:
  agent:
    container_name: scoreserver-agent-${STUDENT_ID}
    build:
      context: ./agent
      dockerfile: Dockerfile
    environment:
      - SCORE_SERVER_IP=192.168.153.128
      - SCORE_SERVER_PORT=8000
      - SCORE_TOKEN=9ebd45b4-000c-4bac-8f12-10dfa2d018d4
      - EXERCISE_ID=yjk43gduzb7a50b
      - PYTHONUNBUFFERED=1

    networks:
      - mynetwork
  student:
    container_name: scoreserver-student-${STUDENT_ID}
    build:
      context: ./student
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME}
        - PASSWORD=${PASSWORD}
    ports:
      - "22"
    networks:
      - mynetwork

networks:
  mynetwork: